### ISSUE TITLE
Using the processBeforeResponse flag

### ISSUE THREAD

**Issue by ryan-0** [seratch/bolt-on-cloud-functions-for-firebase#4]
Hi @seratch, I am building a slack app on cloud functions (for now... cold starts are annoying...) and I think I should be using the `processBeforeResponse` as outlined in  https://github.com/slackapi/bolt-js/pull/444 but having issues figuring out how to use it. Is it as easy as just adding the option to my App constructor? Do I need to move by `ack()` calls to the end of my handler functions or can I keep them at the beginning?

**Comment by seratch** [comment]
Thanks for flagging this! Yes, this example should be updated.

>Is it as easy as just adding the option to my App constructor? 

Yes, it is. If you initialize `ExpressReceiver` manually, you need to set the flag to both `App` and `ExpressReceiver`.

>Do I need to move by ack() calls to the end of my handler functions or can I keep them at the beginning?

No, you don't. When you turn on the option, your app waits for the whole completion of a listener function before sending an HTTP response to Slack regardless of the position of `ack()` calls.

**Comment by ryan-0** [comment]
Thanks! that worked fine!

**Comment by seratch** [comment]
I've updated this example to be up-to-date. Let me close this issue now.
